In [ ]:
'''
Task3 特征选择  
1. TF-IDF原理。
2. 文本矩阵化，使用词袋模型，以TF-IDF特征值为权重。（可以使用Python中TfidfTransformer库）
3. 互信息的原理。
4. 使用第二步生成的特征矩阵，利用互信息进行特征筛选。
5. 参考
文本挖掘预处理之TF-IDF：https://www.cnblogs.com/pinard/p/6693230.html
使用不同的方法计算TF-IDF值：https://www.jianshu.com/p/f3b92124cd2b
sklearn-点互信息和互信息：https://blog.csdn.net/u013710265/article/details/72848755
如何进行特征选择（理论篇）机器学习你会遇到的“坑”：https://baijiahao.baidu.com/s?id=1604074325918456186&wfr=spider&for=pc

'''

In [ ]:
'''
1. TF-IDF原理。
词频-逆文档频（Term Frequency-Inverse DocumentFrequency），
是衡量一个词的在一篇文章中的重性的一套标准。
它与词频，也就是词在文章中出现的次数成正比。
与词在整个与词在整个语料库中出现次数，也就是文档频，成反比，即逆文档频率

'''

In [48]:
'''
2. 文本矩阵化，使用词袋模型，以TF-IDF特征值为权重。（可以使用Python中TfidfTransformer库）
'''
import jieba
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

#定义文本
textAll=''

#读文档
with open(r'cutText2.txt','r') as fw:
    lines = fw.readlines()
#print("==打印从txt文件读取的文本==")
#print(lines)

#拼接文本
for line in lines:
    textAll += line
    
#停用词表：
stopWordsList = [' ','。','，','的','。','.','了','呀']

#中文分词
bagList = jieba.lcut(textAll,cut_all=False)
#print("==分词==")
#print(bagList)
#去停用词
#分到词的列表
wordsList_w = [w for w in bagList if w not in stopWordsList]
print("==分到词,去停用词后==")
print(wordsList_w)
#【去停用词，保留\n换行符，把词再拼成句子用空格隔开，做成符合TF-IDF需要的训练格式。】
#以空格组合词成句,合成符合TF-IDF需要的训练格式
#join成字符串，再以\n分隔存入list中，split
wordsList_str = " ".join(wordsList_w)
wordsList = wordsList_str.split("\n")
print("====以空格组合词成句,合成符合TF-IDF需要的训练格式===")
print(wordsList)


#实例化CountVectorizer词频对象 
#初始化词频统计对象
vector = CountVectorizer(stop_words=stopWordsList)
print("==打印词频统计对象==")
print(vector)
#学习分词得到词频
fitTsVector = vector.fit_transform(wordsList)
#【注意：上面用分好词的词列表wordsList最后算出来TF-IDF值都是1？换成整段文字lines看下】
#【这个要看下面中英文对照，中文也要传句子，但是是分好词的，
#TF-IDF是看词在句中和在篇章中的权重综合。分在自己就没有比对了，当然会是1
#所以上面做一个修改，把分好词的再以空格连接起来组成一组】
#【但这样打印出来的get_feature_names特征词是句子】
#fit_transform和fit一样，是把数据传进来学习，一个参数代表无监督学习，即没有结果，
#找特征是一种无监督学习

#换用以下英文文本做训练
'''
text=[
    "My name is Wang",
    "I come to China to travel",
    "This is a car polupar in China",
    "I love tea and Apple ",
    "The work is to write some papers in science"]
'''
'''
text = [
    '当地 时间 2017 15','日本 神奈川县 横须贺',
      ' 东芝 国际 反应堆 报废 研究 开发 机构 IRID 共同开发 机器人 公开 亮相',
      '这个 30 厘米 直径 13 厘米 水下 机器人 投放 福岛 第一 核电站 机组 反应堆 安全壳 底部 展开 调查'
]
#【注意以上中文和英文的格式对比，中文要传入fit的也必须是句子，只不过是分好词的句子。
#看它的tf-idf重要性要看在句子中的？总之分成当个词一个一个逗开的那种，权重都是1。】
'''

#fitTsVector = vector.fit_transform(text)

print("==打印词频 括号里两位分别是 分类、词id（id可在下面信息对照） 右边值是词频==")
#【也就是说，这一次Count后 fit 训练得到的是词频，传到下面TfidfTransformer的fit里面再训练就得到的是tf-idf
#可以用TfidfVectorizer一步到位算得tf-idf】
print(fitTsVector)
# 每类文本的词频转array
print(fitTsVector.toarray())
# 去重后的词,即特征
print("==去重后的词,即特征==")
print(vector.get_feature_names())
# 每个单词对应的id值
print("==每个单词对应的id值==")
print(vector.vocabulary_)


#实例化TfidfTransformer TF-IDF计算类
transformer = TfidfTransformer()
#用TF-IDF计算器训练上面求得的词频结果，得到每个词的最终TF-IDF
tfidfit = transformer.fit_transform(fitTsVector)
print("==打印每类文本的TF-IDF权重==")
print(tfidfit)


==分到词,去停用词后==
['今年', '汽车', '销售额', '有', '提高', '汽车', '拥有', '辆', '有', '提高', '但是', '道路', '拥堵', '也', '加重', '\n', '中午', '去', '吃', '烤鸭', '要', '减肥', '还是', '少', '吃', '油腻', '多', '吃', '青菜', '健康', '饮食', '\n', '最新', '上映', '影片', '获得', '最高', '票房', '但是', '有刷票', '嫌疑', '\n', '人工智能', '飞速发展', '自然语言', '识别', '是', '人工智能', '一个', '分支', '机器', '学习', '是', '基础', '后面', '还有', '深度', '学习', '这些', '多', '是', '讲', '基础', '算法', '\n']
====以空格组合词成句,合成符合TF-IDF需要的训练格式===
['今年 汽车 销售额 有 提高 汽车 拥有 辆 有 提高 但是 道路 拥堵 也 加重 ', ' 中午 去 吃 烤鸭 要 减肥 还是 少 吃 油腻 多 吃 青菜 健康 饮食 ', ' 最新 上映 影片 获得 最高 票房 但是 有刷票 嫌疑 ', ' 人工智能 飞速发展 自然语言 识别 是 人工智能 一个 分支 机器 学习 是 基础 后面 还有 深度 学习 这些 多 是 讲 基础 算法 ', '']
==打印词频统计对象==
CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None,
        stop_words=[' ', '。', '，', '的', '。', '.', '了', '呀'],
        strip_accents=None, token_patt

In [49]:
#TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
'''

text2=[
    "My name is Wang",
    "I come to China to travel",
    "This is a car polupar in China",
    "I love tea and Apple ",
    "The work is to write some papers in science"]
'''
#实例化 TfidfVectorizer 不用算词频，直接可以算出TF-IDF
tfidf2 = TfidfVectorizer()
rs = tfidf2.fit_transform(wordsList)
print(rs)
#打印看数值是一样的
print(rs.toarray())#变数组
#python公式计算TF-IDF参考：https://www.jianshu.com/p/f3b92124cd2b

  (0, 4)	0.2612568039321974
  (0, 22)	0.5225136078643948
  (0, 35)	0.2612568039321974
  (0, 17)	0.5225136078643948
  (0, 16)	0.2612568039321974
  (0, 5)	0.2107803444058925
  (0, 34)	0.2612568039321974
  (0, 15)	0.2612568039321974
  (0, 9)	0.2612568039321974
  (1, 2)	0.35355339059327373
  (1, 25)	0.35355339059327373
  (1, 7)	0.35355339059327373
  (1, 31)	0.35355339059327373
  (1, 23)	0.35355339059327373
  (1, 36)	0.35355339059327373
  (1, 6)	0.35355339059327373
  (1, 38)	0.35355339059327373
  (2, 5)	0.2743035641495426
  (2, 18)	0.339992197464673
  (2, 1)	0.339992197464673
  (2, 14)	0.339992197464673
  (2, 29)	0.339992197464673
  (2, 19)	0.339992197464673
  (2, 26)	0.339992197464673
  (2, 20)	0.339992197464673
  (2, 12)	0.339992197464673
  (3, 3)	0.4170288281141496
  (3, 37)	0.2085144140570748
  (3, 28)	0.2085144140570748
  (3, 30)	0.2085144140570748
  (3, 0)	0.2085144140570748
  (3, 8)	0.2085144140570748
  (3, 21)	0.2085144140570748
  (3, 13)	0.4170288281141496
  (3, 11)	0.4170288281141

In [ ]:
'''
3. 互信息的原理。
两个事件集合之间的相关性
由于事件A发生与事件B发生相关联而提供的信息量。
在处理分类问题提取特征的时候就可以用互信息来衡量某个特征和特定类别的相关性，如果信息量越大，那么特征和这个类别的相关性越大。
公式：I(A,B) = log_2 P(B|A)/P(B)
A，B的互信息 = log以2为底的 A发生情况下的B的概率除B的概率
'''

In [50]:
#把上面词特征和分类合成DataFrame直观看下
import pandas as pd

print(tfidfit.toarray())
pdDf = pd.DataFrame(tfidfit.toarray())
pdDf

[[0.         0.         0.         0.         0.2612568  0.21078034
  0.         0.         0.         0.2612568  0.         0.
  0.         0.         0.         0.2612568  0.2612568  0.52251361
  0.         0.         0.         0.         0.52251361 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.2612568  0.2612568
  0.         0.         0.        ]
 [0.         0.         0.35355339 0.         0.         0.
  0.35355339 0.35355339 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.35355339
  0.         0.35355339 0.         0.         0.         0.
  0.         0.35355339 0.         0.         0.         0.
  0.35355339 0.         0.35355339]
 [0.         0.3399922  0.         0.         0.         0.27430356
  0.         0.         0.         0.         0.         0.
  0.3399922  0.         0.3399922  0.         0. 

0         1         2         3         4         5         6   \
0  0.000000  0.000000  0.000000  0.000000  0.261257  0.210780  0.000000   
1  0.000000  0.000000  0.353553  0.000000  0.000000  0.000000  0.353553   
2  0.000000  0.339992  0.000000  0.000000  0.000000  0.274304  0.000000   
3  0.208514  0.000000  0.000000  0.417029  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         7         8         9   ...        29        30        31        32  \
0  0.000000  0.000000  0.261257  ...  0.000000  0.000000  0.000000  0.000000   
1  0.353553  0.000000  0.000000  ...  0.000000  0.000000  0.353553  0.000000   
2  0.000000  0.000000  0.000000  ...  0.339992  0.000000  0.000000  0.000000   
3  0.000000  0.208514  0.000000  ...  0.000000  0.208514  0.000000  0.208514   
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

         33        34        35        36        37        38  
0  0.000000  0.261257  0.261257  0.000000  0.000000  0.000000  
1  0.000000  0.000000  0.000000  0.353553  0.000000  0.353553  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3  0.208514  0.000000  0.000000  0.000000  0.208514  0.000000  
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  

[5 rows x 39 columns]

In [47]:
'''
4. 使用上面生成的特征矩阵，利用互信息进行特征筛选。
'''
'''

from sklearn import datasets
from sklearn import metrics as mr
#label=['汽车','电影','美食','计算机']
label=[0,2,1,3,4]
x0 = pdDf[:][0]
print(x0)
print(mr.mutual_info_score(x0.values, label))
'''

'''
#参考
from sklearn import datasets
from sklearn import metrics as mr

iris = datasets.load_iris()
x = iris.data
label = iris.target
x0 = x[:, 0]
x1 = x[:, 1]
x2 = x[:, 2]
x3 = x[:, 3]
#print(x)
#print(x0)
print(label)
xDf = pd.DataFrame(x)
xDf.head()
yDf = pd.DataFrame(label)
yDf.head()
df = pd.concat([xDf,yDf],axis = 1)
df.head()
# 计算各特征与label的互信息
#print(mr.mutual_info_score(x0, label))
#print(mr.mutual_info_score(x1, label))
#print(mr.mutual_info_score(x2, label))
#print(mr.mutual_info_score(x3, label))
'''



0    0.000000
1    0.000000
2    0.000000
3    0.208514
4    0.000000
Name: 0, dtype: float64
0.5004024235381879


'\n#参考\nfrom sklearn import datasets\nfrom sklearn import metrics as mr\n\niris = datasets.load_iris()\nx = iris.data\nlabel = iris.target\nx0 = x[:, 0]\nx1 = x[:, 1]\nx2 = x[:, 2]\nx3 = x[:, 3]\n#print(x)\n#print(x0)\nprint(label)\nxDf = pd.DataFrame(x)\nxDf.head()\nyDf = pd.DataFrame(label)\nyDf.head()\ndf = pd.concat([xDf,yDf],axis = 1)\ndf.head()\n# 计算各特征与label的互信息\n#print(mr.mutual_info_score(x0, label))\n#print(mr.mutual_info_score(x1, label))\n#print(mr.mutual_info_score(x2, label))\n#print(mr.mutual_info_score(x3, label))\n'

In [92]:
'''
#参考
from sklearn import datasets
from sklearn.feature_selection import mutual_info_classif
 
iris = datasets.load_iris()
x = iris.data
label = iris.target
 
mutual_info = mutual_info_classif(x, label, discrete_features= False)
print(mutual_info)

'''
from sklearn import datasets
from sklearn import metrics as mr
iris = datasets.load_iris()
xx = iris.data
print(xx)
print(xx.shape)
print(iris.target)
print(iris.target.shape)

#用互信息提了文本特征
from sklearn.feature_selection import mutual_info_classif
import numpy as np
#x = pdDf[:][:]#tfidfit和rs相同，都用了一套数据，两种方法
#print(x)
x = tfidfit.toarray()
print(x)
print(x.shape)
pdDf['label'] = [0,1,2,3,4]
label = pdDf['label'].values#label值需是矩阵，np.matrix生成矩阵
print(label)
print(label.shape)
#【遗留问题：代入自己数据时有误，待解决 】
#mutual_info = mutual_info_classif(x, label, discrete_features= False)
#print(mutual_info)
x0 = x[:,0]
x1 = x[:,1]
x2 = x[:,2]
x3 = x[:,3]
x4 = x[:,4]
print(mr.mutual_info_score(x0, label))
print(mr.mutual_info_score(x1, label))
print(mr.mutual_info_score(x2, label))
print(mr.mutual_info_score(x3, label))
print(mr.mutual_info_score(x4, label))
#【遗留问题：
#这里特征都分类得分都是一样，原因可能是没有经过拆分训练集，测试集，
#这里还是没有搞懂怎么回事，回头在再下吧。
#】

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.